### ISSUE TITLE
Why StrQueue?

### ISSUE THREAD

**Issue by drakstik** [hakjoonlee/CS4500-A1P2#12]
I find your StrQueue implementation unnecessary, because you can easily pass in a String as an Object since our Array class (which we use in the implementation of Queue & StrQueue) accepts String as an Object. So why StrQueue? I don't mind it being there, but why?

**Comment by kaylindevchand** [comment]
@drakstik see #4

**Comment by andrewstam** [comment]
Hopefully that answered your question - closing this thread, thanks for linking to the other post @kaylindevchand
