### ISSUE TITLE
test-queue.cpp - test_queue_error_handling() uses try/catch

### ISSUE THREAD

**Issue by gouldk** [hakjoonlee/CS4500-A1P2#2]
CwC stipulations specifically say not to use try/catch or exceptions in our code. We are using asserts as specified in CwC in our implementation. We don't have any way to pass the first peek test, which tries to use try/catch on an assert statement. (Asserts aren't stopped by try/catch)

**Comment by hakjoonlee** [comment]
Apologies for this issue. We'll rewrite our test file to exclude any try-catch statements and push it to our repository sometime tomorrow. Thanks for catching this error.
