### ISSUE TITLE
I Love your string.h & object.h, but we have to make a choice.

### ISSUE THREAD

**Issue by drakstik** [hakjoonlee/CS4500-A1P2#8]
To everybody implementing this Queue:
We have a choice to make, so please reply or like this comment and make your opinion heard. Which object & string interfaces do we want to use?:

1. Professor Jan's https://piazza.com/class/k51bluky59n2jr?cid=166
2. This Guy's: https://piazza.com/class/k51bluky59n2jr?cid=345

I prefer Jan's because it is clean and comprehensive. The two are not too different, but let's make that choice now guys. Thanks.

**Comment by kaylindevchand** [comment]
I prefer the way it is now, option 2.

**Comment by csstransky** [comment]
I prefer option 2 because our assigned Array and Map repos also use Bishop's code.

**Comment by hakjoonlee** [comment]
Okay, looks like we'll keep the current Object and String files. Thanks for bringing up the issue, and thanks to everyone for their replies.
